### ISSUE TITLE
Don't give warning if channel name is all lowercase

### ISSUE THREAD

**Issue by BostonZcash** [ZbayApp/zbay#96] opened 2020-06-10 13:15 UTC
**Version:** 1.0.66-dev-linux-18-2 (appimage)

On the `'Create a new channel'` dialogue box, even if the entered channel name is all lowercase, a warning still appears that `'Your channel will be created as...'`

This leads one to think there's still some disallowed character in the entered name, despite there not being so.

This notice should only be shown if the name doesn't conform.

**Comment by holmesworcester** [comment] 2020-06-17 15:15
duplicate of #106 (though you couldn't have possibly known this so no worries and thanks for the bug report!)

**Closed by holmesworcester** 2020-06-17 15:15 UTC
