### ISSUE TITLE
Error when purchasing offer item (blank white screen, red alert saying message not sent)

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#248] opened 2020-07-04 17:26 UTC
Steps to reproduce:

1. join channel "#---tst---"
2. purchase first "#postcards" item
3. send funds

Expected: it works, and opens up a thread with you and seller.

Actual: blank white screen in message view area, and alert saying message could not be sent, check node connection. 

Note that the offer item does not show the user's correct name (anon, see conversation in channel) so something about the offer metadata got broken. Hypothesis: offer metadata is not correct, so no chat with user can be displayed, so address is not correct, and message cannot be sent.

**Comment by NorbertBodziony** [comment] 2020-07-10 06:51
This offer seems to be broken maybe created using faulty version. I have not found a reason for that but I added filter do hide broken offers just in case.

**Comment by NorbertBodziony** [comment] 2020-07-10 06:55
#291

**Comment by holmesworcester** [comment] 2020-07-10 14:01
This was just two releases ago so the bug is probably still present. Do we
know specifically what in the offer broke?

**Comment by NorbertBodziony** [comment] 2020-07-13 08:21
Fix for this problem is not in current release. I fixed one issue that caused mismatch in signature but I can't say for sure that was the issue. So far i am unable to reproduce this bug.

**Closed** 2020-07-17 13:24 UTC
Labels: bug, done
